Secret key
TIS2016/Narodna-transfuzna-sluzba pull request #29
Opened 2016-12-10 11:08 UTC by TrubacJakub

2016-12-10 13:11 UTC, mskrip requested changes

2016-12-10 13:11 UTC, mskrip commented on isnts/views/auth.py
> +                nts_list = NTS.objects.all()
toto sa da robit krajsie a setrit aj pamat aj rychlost, pozri si query funkciu `Model.objects.filter(parameter='value')`. Aby si to nemusel nacitavat cele a prechadzat to v cykle

2016-12-10 13:11 UTC, mskrip commented on isnts/views/superuser.py
> +                nts.secret_key = data['secret_key_new2']
Urcite toto nechceme robit, tu treba pouzit nejaku kryptovaciu funkciu napr `make_password(password, salt=None, hasher='default')`, aby sa nedali tieto kluce vytahovat z databazy.

2016-12-10 15:16 UTC, TrubacJakub commented on isnts/views/superuser.py
> +                nts.secret_key = data['secret_key_new2']
Na to som zabudol sry

2016-12-11 15:24 UTC, mskrip approved these changes

2016-12-11 15:25 UTC, merged